export const flashSaleProducts = [
  {
    id: 1,
    name: "AK-900 Wired Keyboard",
    image: "https://m.media-amazon.com/images/I/71w6l5pGQbL._AC_UL1500_.jpg",
    price: 960,
    originalPrice: 1160,
    rating: 4,
    reviews: 75,
    isFavorite: false,
    discount: 35,
  },
  {
    id: 2,
    name: "Logitech G502 Mouse",
    image: "https://m.media-amazon.com/images/I/61mpMH5TzkL._AC_UL1500_.jpg",
    price: 120,
    originalPrice: 150,
    rating: 4.5,
    reviews: 120,
    isFavorite: true,
    discount: 20,
  },
  {
    id: 3,
    name: "Samsung 27\" Monitor",
    image: "https://m.media-amazon.com/images/I/81QpkIctqPL._AC_UL1500_.jpg",
    price: 300,
    originalPrice: 350,
    rating: 4.7,
    reviews: 210,
    isFavorite: false,
    discount: 15,
  },
  {
    id: 4,
    name: "Sony WH-1000XM4",
    image: "https://m.media-amazon.com/images/I/71o8Q5XJS5L._AC_UL1500_.jpg",
    price: 250,
    originalPrice: 320,
    rating: 4.8,
    reviews: 340,
    isFavorite: true,
    discount: 22,
  },
  {
    id: 5,
    name: "Apple iPad 10.2\"",
    image: "https://m.media-amazon.com/images/I/61NGnpjoRDL._AC_UL1500_.jpg",
    price: 400,
    originalPrice: 450,
    rating: 4.6,
    reviews: 180,
    isFavorite: false,
    discount: 11,
  },
  {
    id: 6,
    name: "JBL Flip 6 Speaker",
    image: "https://m.media-amazon.com/images/I/71+F7lFQKGL._AC_UL1500_.jpg",
    price: 99,
    originalPrice: 129,
    rating: 4.4,
    reviews: 95,
    isFavorite: false,
    discount: 23,
  },
  {
    id: 7,
    name: "Canon EOS M50",
    image: "https://m.media-amazon.com/images/I/81E5g5l5QbL._AC_UL1500_.jpg",
    price: 650,
    originalPrice: 750,
    rating: 4.5,
    reviews: 60,
    isFavorite: true,
    discount: 13,
  },
  {
    id: 8,
    name: "Nintendo Switch",
    image: "https://m.media-amazon.com/images/I/61-PblYntsL._AC_UL1500_.jpg",
    price: 299,
    originalPrice: 349,
    rating: 4.9,
    reviews: 500,
    isFavorite: false,
    discount: 14,
  },
  {
    id: 9,
    name: "Dell XPS 13",
    image: "https://m.media-amazon.com/images/I/71w6l5pGQbL._AC_UL1500_.jpg",
    price: 1200,
    originalPrice: 1350,
    rating: 4.7,
    reviews: 80,
    isFavorite: false,
    discount: 11,
  },
  {
    id: 10,
    name: "GoPro HERO10",
    image: "https://m.media-amazon.com/images/I/71QKQwQdKDL._AC_UL1500_.jpg",
    price: 399,
    originalPrice: 499,
    rating: 4.6,
    reviews: 110,
    isFavorite: true,
    discount: 20,
  },
];
