export const explorerProducts = [
  {
    id: 1,
    name: "Breed Dry Dog Food",
    image: "https://m.media-amazon.com/images/I/81vpsIs58WL._AC_UL1500_.jpg",
    price: 100,
    rating: 3.5,
    reviews: 35,
    isFavorite: false,
    isNew: false,
    discount: null,
    colorDots: [],
  },
  {
    id: 2,
    name: "CANON EOS DSLR Camera",
    image: "https://m.media-amazon.com/images/I/71EWRyqzw0L._AC_UL1500_.jpg",
    price: 360,
    rating: 4.5,
    reviews: 95,
    isFavorite: true,
    isNew: false,
    discount: null,
    showAddToCart: true,
    colorDots: [],
  },
  {
    id: 3,
    name: "ASUS FHD Gaming Laptop",
    image: "https://m.media-amazon.com/images/I/81Yb5n4lHCL._AC_UL1500_.jpg",
    price: 700,
    rating: 5,
    reviews: 325,
    isFavorite: false,
    isNew: false,
    discount: null,
    showAddToCart: true,
    colorDots: [],
  },
  {
    id: 4,
    name: "Curology Product Set",
    image: "https://m.media-amazon.com/images/I/61QKQwQdKDL._AC_UL1500_.jpg",
    price: 500,
    rating: 4,
    reviews: 145,
    isFavorite: false,
    isNew: false,
    discount: null,
    colorDots: [],
  },
  {
    id: 5,
    name: "Kids Electric Car",
    image: "https://m.media-amazon.com/images/I/71QKQwQdKDL._AC_UL1500_.jpg",
    price: 960,
    rating: 4.5,
    reviews: 65,
    isFavorite: true,
    isNew: true,
    discount: null,
    colorDots: ["bg-red-500", "bg-black"],
  },
  {
    id: 6,
    name: "Jr. Zoom Soccer Cleats",
    image: "https://m.media-amazon.com/images/I/71w6l5pGQbL._AC_UL1500_.jpg",
    price: 1160,
    rating: 5,
    reviews: 35,
    isFavorite: false,
    isNew: true,
    discount: null,
    colorDots: ["bg-lime-400", "bg-black"],
  },
  {
    id: 7,
    name: "GPII Shooter USB Gamepad",
    image: "https://m.media-amazon.com/images/I/61nCqYb1c+L._AC_SL1500_.jpg",
    price: 660,
    rating: 4.5,
    reviews: 55,
    isFavorite: false,
    isNew: false,
    discount: null,
    colorDots: ["bg-black", "bg-red-500"],
  },
  {
    id: 8,
    name: "Quilted Satin Jacket",
    image: "https://m.media-amazon.com/images/I/71w6l5pGQbL._AC_UL1500_.jpg",
    price: 660,
    rating: 4,
    reviews: 55,
    isFavorite: true,
    isNew: false,
    discount: null,
    colorDots: ["bg-black", "bg-green-900"],
  },
];
