export const wishlistProducts = [
  {
    id: 1,
    name: 'Gucci duffle bag',
    image: 'https://i.imgur.com/1.jpg',
    price: 960,
    originalPrice: 1160,
    discount: 35,
    rating: 4.8,
    reviews: 120,
    isFavorite: true,
  },
  {
    id: 2,
    name: 'RGB liquid CPU Cooler',
    image: 'https://i.imgur.com/2.jpg',
    price: 1960,
    rating: 4.7,
    reviews: 80,
    isFavorite: false,
  },
  {
    id: 3,
    name: 'GP11 Shooter USB Gamepad',
    image: 'https://i.imgur.com/3.jpg',
    price: 550,
    rating: 4.6,
    reviews: 65,
    isFavorite: false,
  },
  {
    id: 4,
    name: 'Quilted Satin Jacket',
    image: 'https://i.imgur.com/4.jpg',
    price: 750,
    rating: 4.9,
    reviews: 40,
    isFavorite: true,
  },
];

export const justForYouProducts = [
  {
    id: 1,
    name: 'ASUS FHD Gaming Laptop',
    image: 'https://i.imgur.com/11.jpg',
    price: 960,
    originalPrice: 1160,
    discount: 35,
    rating: 4.8,
    reviews: 65,
    isFavorite: false,
  },
  {
    id: 2,
    name: 'IPS LCD Gaming Monitor',
    image: 'https://i.imgur.com/12.jpg',
    price: 1160,
    rating: 4.7,
    reviews: 65,
    isFavorite: false,
  },
  {
    id: 3,
    name: 'HAVIT HV-G92 Gamepad',
    image: 'https://i.imgur.com/13.jpg',
    price: 560,
    rating: 4.6,
    reviews: 65,
    isFavorite: false,
  },
  {
    id: 4,
    name: 'AK-900 Wired Keyboard',
    image: 'https://i.imgur.com/14.jpg',
    price: 200,
    rating: 4.5,
    reviews: 65,
    isFavorite: false,
  },
];
