export const bestSellerProducts = [
  {
    id: 1,
    name: "The north coat",
    image: "https://m.media-amazon.com/images/I/71w6l5pGQbL._AC_UL1500_.jpg",
    price: 260,
    originalPrice: 360,
    rating: 4.5,
    reviews: 65,
    isFavorite: false,
    discount: null,
  },
  {
    id: 2,
    name: "Gucci duffle bag",
    image: "https://m.media-amazon.com/images/I/61vQpQJpKDL._AC_UL1500_.jpg",
    price: 960,
    originalPrice: 1160,
    rating: 4.5,
    reviews: 65,
    isFavorite: true,
    discount: null,
  },
  {
    id: 3,
    name: "RGB liquid CPU Cooler",
    image: "https://m.media-amazon.com/images/I/71QkQwQdKDL._AC_UL1500_.jpg",
    price: 160,
    originalPrice: 170,
    rating: 4.5,
    reviews: 65,
    isFavorite: false,
    discount: null,
  },
  {
    id: 4,
    name: "Small BookSelf",
    image: "https://m.media-amazon.com/images/I/71QKQwQdKDL._AC_UL1500_.jpg",
    price: 360,
    originalPrice: 400,
    rating: 4.5,
    reviews: 65,
    isFavorite: false,
    discount: null,
  },
];
